### ISSUE TITLE
Data sync/transfer issue between DataSpace and Discovery

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_discovery#399]
This was reported by an end-user within the PULibrary Slack Channel #digital_open_data_and_research:

> Hello! It looks like there may be a data sync/transfer issue between DataSpace and Discovery. We've published 4 datasets this year (http://arks.princeton.edu/ark:/88435/dsp01gt54kr255, http://arks.princeton.edu/ark:/88435/dsp01fq977z011, http://arks.princeton.edu/ark:/88435/dsp01c247dw32c, and http://arks.princeton.edu/ark:/88435/dsp01j098zf33b), but none of these are appearing in Discovery. The earliest was published on Jan 30, 2023

(https://pulibrary.slack.com/archives/C01555TP6HE/p1679500357138449)

**Comment by hectorcorrea** [comment]
Manually running the reindex in production took care of these issue, the 4 records are now available in PDC Discovery:
* [dsp01gt54kr255](https://datacommons.princeton.edu/discovery/?search_field=all_fields&q=dsp01gt54kr255)
* [dsp01fq977z011](https://datacommons.princeton.edu/discovery/?search_field=all_fields&q=dsp01fq977z011)
* [dsp01c247dw32c](https://datacommons.princeton.edu/discovery/?search_field=all_fields&q=dsp01c247dw32c) 
* [dsp01j098zf33b](https://datacommons.princeton.edu/discovery/?search_field=all_fields&q=dsp01j098zf33b) 

We did notice that the problem is only in production, the four records were already in staging. The culprit seems to be that we have an extra condition in production that is stopping the process. 

The [reindex task](https://github.com/pulibrary/pdc_discovery/blob/main/lib/tasks/index.rake#L5-L13) calls the [delete index task](https://github.com/pulibrary/pdc_discovery/blob/main/lib/tasks/index.rake#L30-L35) and that is not allowed in production.
