### ISSUE TITLE
Clean up Solr collections in production

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_discovery#414]
This follows the resolution of the troubleshooting and issue resolution led by @hectorcorrea. This *must* not be resolved until at least 04/11/23 please.

**Comment by hectorcorrea** [comment]
And check is we also need to remove `pdc-discovery-production-2` since now there is a `pdc-discovery-production-3` (see original ticket #410 for details)

**Comment by hectorcorrea** [comment]
Final status:
* Recreated collection `pdc-discovery-production-1` with two replicas. 
* Alias `pdc-discovery-production` points to this new collection.
* Deleted collection `pdc-discovery-production-3` that had only one replica (not needed now that figured out the reindex issue, see PR #419).
* Deleted collection `pdc-discovery-production-2` since it was created just for testing.
