### ISSUE TITLE
We cannot assume all DOIs will have the same prefix

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_discovery#470]
When we first built PDC Discovery we assumed (because we were told) that all the DOIs would have the Princeton DOI prefix. This is not true. Unfortunately, we have hard-coded the Princeton DOI prefix in several places.

![Screenshot 2023-08-08 at 4 07 08 PM](https://github.com/pulibrary/pdc_discovery/assets/65608/e0af7337-8ffe-4ffb-b59d-9c4f9e2a7013)
![Screenshot 2023-08-08 at 4 06 16 PM](https://github.com/pulibrary/pdc_discovery/assets/65608/da068b82-91a8-4a57-b23d-4880ad675847)

**Comment by hectorcorrea** [comment]
Notice that for the particular record in question [Enhancement of edge turbulence concomitant with ELM suppression during boron powder injection in EAST](https://datacommons.princeton.edu/discovery/catalog/doi-10-11578-1814960) the `pdc_describe_match` was successful because a PDC Describe match was found by ARK and therefore we didn't have to search by DOI.

**Comment by hectorcorrea** [comment]
The hard coded value is currently only used in the DataSpace import so we are probably OK since records coming from DataSpace will have an ARK. 

Closing issue for now. If we run into other DOI prefixes we can re-open and add the other known prefixes to this logic.
